---
    name: Checks

    on :
        push:
            branches:
                - main

    jobs:
        GDAL_installation:
            name: Install GDAL
            runs-on: ubuntu-latest
            steps:
                - name: Checkout
                  uses: actions/checkout@v3

                - name: Setup Python
                  uses: actions/setup-python@v3.0.0
                  with:
                    python-version: 3.10.1
                    cache: 'pip'
                    
                - name: Create and start virtual environment
                  run: |
                      python -m venv venv
                      source venv/bin/activate
                - name: Install dependencies
                  run: pip install gdal
